version: "3.9"

services:
  posts_api:
    build:
      context: .
      dockerfile: posts.DockerFile
    container_name: plantar_posts_api
    environment:
      - API_URL=${POSTS_API_URL}
    restart: always
    volumes:
      - ./api/posts:/usr/src/code/api/posts
      - /usr/src/code/api/posts/node_modules
    ports:
      - 3333:3333

  client:
    build:
      context: .
      dockerfile: client.DockerFile
    container_name: plantar_client
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_POSTS_API_BASE_URL=${POSTS_API_URL}
    restart: always
    volumes:
      - ./client:/usr/src/code/client
      - /usr/src/code/client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - posts_api
