version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: client.DockerFile
    container_name: plantar_client
    environment:
      - WATCHPACK_POLLING=true
      # - REACT_APP_WEBSERVICE_BASE_URL=${WEBSERVICE_API_URL}
    restart: always
    volumes:
      - ./client:/usr/src/code/client
      - /usr/src/code/client/node_modules
    ports:
      - 3000:3000
    # depends_on:
    #   - webservice
