version: "3.9"

services:

  database:
    image: postgres:15
    container_name: plantar_db
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

  posts_api:
    build:
      context: .
      dockerfile: posts.DockerFile
    container_name: plantar_posts_api
    environment:
      - API_URL=${POSTS_API_URL}
    restart: always
    volumes:
      - ./api/posts:/usr/src/code/api/posts
      - /usr/src/code/api/posts/node_modules
    ports:
      - 3333:3333

  planting_calendar_api:
    build:
      context: .
      dockerfile: plantingCalendar.DockerFile
    container_name: plantar_planting_calendar_api
    environment:
      - API_URL=${PLANTING_CALENDAR_API_URL_V1}
    restart: always
    volumes:
      - ./api/planting-calendar:/usr/src/code/api/planting-calendar
    ports:
      - 8000:8000

  client:
    build:
      context: .
      dockerfile: client.DockerFile
    container_name: plantar_client
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_POSTS_API_BASE_URL=${POSTS_API_URL}
      - REACT_APP_PLANTING_CALENDAR_API_BASE_URL_V1=${PLANTING_CALENDAR_API_URL_V1}
      - REACT_APP_GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    restart: always
    volumes:
      - ./client:/usr/src/code/client
      - /usr/src/code/client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - posts_api
      - planting_calendar_api
